
#数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations:
    - classpath:/resources/
    
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
#mybatis ---mapper对的扫描路径
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  
logging:
  level:
    com.st.dao: debug